name = "almeida-portafolio"
main = "functions/api/chat.js"
compatibility_date = "2026-09-17"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "40f17acc9c554ff994f2ca0c5f15973b"

[assets]
directory = "./web"
run_worker_first = ["/api/*"]